text="Hello World"
print(text[0])
print(text[1:5])
print(text[:5])
print(text[6:])
print(text[-3:-1])
print(text[-3:])
print(type(text[0]))
print(type(text[0:2]))
print("Below is the string methods")
print(dir(str))
print("Below will print help text on string")
print(help(str))
