stringSet= input("enter a text containing s: ")
print("You entered : ")
print(stringSet)
print("Now s is replaced with z and the new text is: ")
stringSetNew = stringSet.replace("s","z")
print(stringSetNew)
stringSetNew2=stringSet.replace("s","z",2)
print(stringSetNew2)
